Add check for approved PR's which are ready for merge

diff --git a/.github/workflows/merge.yml b/.github/workflows/merge.yml
--- a/.github/workflows/merge.yml
+++ b/.github/workflows/merge.yml
@@ -45,6 +45,25 @@ jobs:
           echo TAG_VERSION="v$version" >> "$GITHUB_ENV"
           echo RELEASE_NOTES_FILE="./release-docs/CFF-${version}.md" >> "$GITHUB_ENV"
 
+      - name: Check PR's approved
+        run: |
+            function prCheck () {
+              REPO=$1
+              BASE=$2
+              COUNT=$(gh pr list --repo $REPO --json title,mergeStateStatus,state,reviews --state OPEN --base $BASE --head $RELEASE_BRANCH --jq '.[] | [ select(.mergeStateStatus == "CLEAN" and .reviews[].state == "APPROVED") ] | length ')
+              if [ "$COUNT" -ne 1 ]; then
+                echo "Error: PR for merging $REPO $RELEASE_BRANCH into $BASE needs to be ready to merge and approved." >&2
+                exit 1
+              fi
+            }
+            prCheck $GITHUB_REPOSITORY_OWNER/flood-app master
+            prCheck $GITHUB_REPOSITORY_OWNER/flood-app development
+            prCheck $GITHUB_REPOSITORY_OWNER/flood-service master
+            prCheck $GITHUB_REPOSITORY_OWNER/flood-service development
+        env:
+          # create classic PAT and then run `gh secret set GH_WORKFLOW`
+          GH_TOKEN: ${{ secrets.GH_WORKFLOW }}
+
       - name: Check branch exists
         run: |
           if ! git ls-remote --exit-code origin "refs/heads/${RELEASE_BRANCH}"; then
